import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
opacity = 0.9

[font]
normal = { family = "Mononoki Nerd Font", style = "Regular" }
size = 17.0
offset.y = 2

[cursor]
style = { shape = "Beam", blinking = "Always" }

[env]
TERM = "xterm-256color"
