[manager]
show_hidden = true
sort_by = "btime"
# linemode = "size"
show_symlink = true

[preview]
wrap = "yes"

[opener]
open = [{ run = 'xdg-open "$@"', desc = "Open Editable Files" }]
open_images = [{ run = 'swayimg "$@"', desc = "Open Images using Imv" }]
open_pdf = [{ run = 'zathura "$@"', desc = "Open PDFs using zathura" }]

[open]
prepend_rules = [
  { name = "*.jpg", use = "open_images" },
  { name = "*.png", use = "open_images" },
  { name = "*.jpeg", use = "open_images" },
  { name = "*.webp", use = "open_images" },
  { name = "*.gif", use = "open_images" },
  { name = "*.pdf", use = "open_pdf" },
]

# [[actions]]
# name = "unzip"
# command = "unzip {input} -d {output_dir}"
#
# [[extensions]]
# extension = "zip"
# action = "unzip"
