[pyprland]

plugins = ["scratchpads", "magnify"]

[scratchpads.term]
animation = "fromTop"
command = "foot -a foot-dropterm"
class = "foot-dropterm"
size = "75% 60%"

[scratchpads.editor]
animation = "fromLeft"
command = "mousepad"
class = "mousepad-scratchpad"
size = "40% 75%"
