# Aliases
alias pacs='sudo pacman -S'
alias pacrns='sudo pacman -Rns'
alias pacsyu='sudo pacman -Syu'
alias pacsyy='sudo pacman -Syy'
alias pacsyyu='sudo pacman -Syyu'
alias gen_grub_config='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias update_mirrors='sudo reflector -c India --sort rate --latest 5 --protocol https --save /etc/pacman.d/mirrorlist'
alias ls='lsd'
alias ll='lsd -l --header'
alias la='lsd -la --header'
alias lt='lsd --tree'
alias system_cleanup='rm -rf ~/.cache/* && yay -Sc && sudo journalctl --vacuum-time=1hour'
alias error_logs='sudo journalctl -p 3 -xb'
alias md='mkdir'
alias rd='rmdir'
alias grep='rg'
alias man='batman'
alias cd='z'
alias cdi='zi'
alias ..='z ..'
alias ....='z ../..'
alias cmd='command'
alias clock='tty-clock -c'
#
